[package]
name = "frametrace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
mediasoup = "0.9.0"
serde = "1.0.130"
